<?php

declare(strict_types=1);

namespace Jessecruz\ResendInbox;

/**
 * Recognizes machine-generated inbound mail (auto-replies, bounces, bulk
 * mail) so it can be stored without raising alerts, and an autoresponder
 * cannot start an alert loop.
 */
final class AutoReplyDetector
{
    /**
     * @param  array<array-key, mixed>  $headers
     */
    public static function isAutoGenerated(array $headers, string $fromAddress): bool
    {
        $autoSubmitted = mb_strtolower(trim((string) Headers::get($headers, 'Auto-Submitted')));

        if ($autoSubmitted !== '' && $autoSubmitted !== 'no') {
            return true;
        }

        if (in_array(mb_strtolower(trim((string) Headers::get($headers, 'Precedence'))), ['bulk', 'junk', 'auto_reply'], true)) {
            return true;
        }

        if (Headers::get($headers, 'X-Autoreply') !== null || Headers::get($headers, 'X-Autorespond') !== null) {
            return true;
        }

        $address = EmailAddress::address($fromAddress);
        $localPart = mb_strtolower(strstr($address, '@', true) ?: $address);

        return in_array($localPart, ['mailer-daemon', 'postmaster'], true);
    }
}
