<?php

declare(strict_types=1);

namespace Jessecruz\ResendInbox;

use DateTimeImmutable;
use DateTimeZone;
use Throwable;

/**
 * Full inbound email as returned by Resend's received-emails API.
 */
final readonly class ReceivedEmail
{
    /**
     * @param  list<string>  $to
     * @param  list<string>  $cc
     * @param  list<string>  $replyTo
     * @param  list<string>  $receivedFor
     * @param  array<array-key, mixed>  $headers
     * @param  list<array{id: string, filename: string|null, content_type: string|null, size: int|null}>  $attachments
     */
    public function __construct(
        public string $resendId,
        public string $fromAddress,
        public ?string $fromName,
        public array $to,
        public array $cc,
        public array $replyTo,
        public array $receivedFor,
        public string $subject,
        public ?string $html,
        public ?string $text,
        public ?string $messageId,
        public array $headers,
        public array $attachments,
        public DateTimeImmutable $receivedAt,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromApi(array $data): self
    {
        $from = EmailAddress::parse(self::string($data['from'] ?? null) ?? '');

        return new self(
            resendId: self::string($data['id'] ?? null) ?? '',
            fromAddress: $from['address'],
            fromName: $from['name'],
            to: self::strings($data['to'] ?? []),
            cc: self::strings($data['cc'] ?? []),
            replyTo: array_map(EmailAddress::address(...), self::strings($data['reply_to'] ?? [])),
            receivedFor: self::strings($data['received_for'] ?? []),
            subject: self::string($data['subject'] ?? null) ?? '',
            html: self::string($data['html'] ?? null),
            text: self::string($data['text'] ?? null),
            messageId: EmailAddress::messageId(self::string($data['message_id'] ?? null)),
            headers: is_array($data['headers'] ?? null) ? $data['headers'] : [],
            attachments: self::attachments($data['attachments'] ?? null),
            receivedAt: self::date($data['created_at'] ?? null),
        );
    }

    /**
     * Every address the email was delivered to: envelope recipients, To and Cc.
     *
     * @return list<string>
     */
    public function recipients(): array
    {
        return [...$this->receivedFor, ...$this->to, ...$this->cc];
    }

    public function header(string $name): ?string
    {
        return Headers::get($this->headers, $name);
    }

    /**
     * @return list<string>
     */
    public function inReplyTo(): array
    {
        return EmailAddress::messageIds($this->header('In-Reply-To'));
    }

    /**
     * @return list<string>
     */
    public function references(): array
    {
        return EmailAddress::messageIds($this->header('References'));
    }

    /**
     * Message-IDs this email answers, In-Reply-To first.
     *
     * @return list<string>
     */
    public function referencedMessageIds(): array
    {
        return array_values(array_unique([...$this->inReplyTo(), ...$this->references()]));
    }

    public function isAutoGenerated(): bool
    {
        return AutoReplyDetector::isAutoGenerated($this->headers, $this->fromAddress);
    }

    private static function string(mixed $value): ?string
    {
        return is_scalar($value) ? (string) $value : null;
    }

    /**
     * @return list<string>
     */
    private static function strings(mixed $value): array
    {
        if (is_string($value)) {
            return [$value];
        }

        return is_array($value) ? array_values(array_map(strval(...), array_filter($value, is_scalar(...)))) : [];
    }

    /**
     * @return list<array{id: string, filename: string|null, content_type: string|null, size: int|null}>
     */
    private static function attachments(mixed $value): array
    {
        $attachments = [];

        foreach (is_array($value) ? $value : [] as $attachment) {
            if (! is_array($attachment)) {
                continue;
            }

            $attachments[] = [
                'id' => self::string($attachment['id'] ?? null) ?? '',
                'filename' => self::string($attachment['filename'] ?? null),
                'content_type' => self::string($attachment['content_type'] ?? null),
                'size' => is_numeric($attachment['size'] ?? null) ? (int) $attachment['size'] : null,
            ];
        }

        return $attachments;
    }

    /**
     * The timestamp in PHP's default timezone: ORMs store the wall-clock time
     * without its offset and read it back in that timezone.
     */
    private static function date(mixed $value): DateTimeImmutable
    {
        if (is_string($value) && $value !== '') {
            try {
                return (new DateTimeImmutable($value))->setTimezone(new DateTimeZone(date_default_timezone_get()));
            } catch (Throwable) {
                // Fall through to "now" for a malformed timestamp.
            }
        }

        return new DateTimeImmutable;
    }
}
