<?php

declare(strict_types=1);

use Jessecruz\ResendInbox\AutoReplyDetector;

it('recognizes machine generated mail', function (array $headers, string $from) {
    expect(AutoReplyDetector::isAutoGenerated($headers, $from))->toBeTrue();
})->with([
    'auto-submitted' => [['Auto-Submitted' => 'auto-replied'], 'maria@acme.com'],
    'header name in lowercase' => [['auto-submitted' => 'auto-generated'], 'maria@acme.com'],
    'bulk precedence' => [['Precedence' => 'bulk'], 'maria@acme.com'],
    'auto reply precedence' => [['Precedence' => 'auto_reply'], 'maria@acme.com'],
    'x-autoreply' => [['X-Autoreply' => 'yes'], 'maria@acme.com'],
    'x-autorespond' => [['X-Autorespond' => 'yes'], 'maria@acme.com'],
    'mailer daemon' => [[], 'MAILER-DAEMON@mx.acme.com'],
    'postmaster with a name' => [[], 'Mail System <postmaster@acme.com>'],
]);

it('lets mail written by a person through', function (array $headers) {
    expect(AutoReplyDetector::isAutoGenerated($headers, 'maria@acme.com'))->toBeFalse();
})->with([
    'no headers' => [[]],
    'auto-submitted no' => [['Auto-Submitted' => 'no']],
    'list precedence' => [['Precedence' => 'list']],
]);
