<?php

declare(strict_types=1);

it('maps the receiving api response', function () {
    $email = receivedEmail([
        'reply_to' => ['Maria <Replies@Acme.com>'],
        'headers' => ['in-reply-to' => '<ours-2@elenya.app>', 'References' => '<ours-1@elenya.app> <ours-2@elenya.app>'],
    ]);

    expect($email->resendId)->toBe('rcv_1')
        ->and($email->fromAddress)->toBe('maria@acme.com')
        ->and($email->fromName)->toBe('Maria Silva')
        ->and($email->replyTo)->toBe(['replies@acme.com'])
        ->and($email->messageId)->toBe('abc-123@mail.acme.com')
        ->and($email->attachments)->toBe([['id' => 'att_1', 'filename' => 'rfp.pdf', 'content_type' => 'application/pdf', 'size' => 2048]])
        ->and($email->receivedAt->format(DATE_ATOM))->toBe('2026-09-14T12:00:00+00:00')
        ->and($email->recipients())->toBe(['contato@elenya.app', 'contato@elenya.app'])
        ->and($email->inReplyTo())->toBe(['ours-2@elenya.app'])
        ->and($email->referencedMessageIds())->toBe(['ours-2@elenya.app', 'ours-1@elenya.app'])
        ->and($email->isAutoGenerated())->toBeFalse();
});

it('tolerates missing and malformed fields', function () {
    $email = receivedEmail([
        'to' => 'single@elenya.app',
        'cc' => null,
        'html' => null,
        'message_id' => null,
        'headers' => 'not-an-array',
        'attachments' => ['junk', ['id' => 'att_2', 'size' => 'big']],
        'created_at' => 'not a date',
    ]);

    expect($email->to)->toBe(['single@elenya.app'])
        ->and($email->cc)->toBe([])
        ->and($email->html)->toBeNull()
        ->and($email->messageId)->toBeNull()
        ->and($email->headers)->toBe([])
        ->and($email->attachments)->toBe([['id' => 'att_2', 'filename' => null, 'content_type' => null, 'size' => null]])
        ->and($email->receivedAt)->toBeInstanceOf(DateTimeImmutable::class);
});
